name: Vapor OAuth

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: '*'

jobs:
  ubuntu_test:
    name: Ubuntu Build & Test
    runs-on: ubuntu-22.04
    container: swift:6.0
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test
  macos_test:
    name: macOS Build & Test
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test
